name: Build Windows
run-name: Build On Windows

on:
  push:
    branches: [master]

jobs:
  build_release:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: 'true'
        
      - name: Build Config
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release --target "install"